# playbook.yml for React
---
- hosts: frontend
  become: true
  tasks:
    - name: copy files
      copy:
        src: ./frontend/
        dest: /var/www/frontend/
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: install npm depend
      command: npm install
      args:
        chdir: /var/www/frontend/

    - name: build React app
      command: npm run build
      args:
        chdir: /var/www/frontend/