# playbook.yml для Node.js
---
- hosts: backend
  become: true
  tasks:
    - name: Add repo Node.js
      apt_repository:
        repo: 'deb https://deb.nodesource.com/node_16.x focal main'
        state: present
        filename: 'nodesource'

    - name: Update cache APT
      apt:
        update_cache: yes

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: copy backend's files
      copy:
        src: ./backend/
        dest: /var/www/backend/
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Install npm dependencies
      command: npm install
      args:
        chdir: /var/www/backend/

    - name: run backend
      command: pm2 start npm --name "backend" -- start
      args:
        chdir: /var/www/backend/
