---
- name: Install Nginx Web Server on RedHat Family
  yum:
    name=nginx
    state=latest
  when:
    ansible_os_family == "RedHat"
  notify:
    - nginx systemd

- name: Install Nginx Web Server on Linux Family
  apt:
    name=nginx
    state=latest
  when:
    ansible_os_family == "Linux"
  notify:
    - nginx systemd