name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Install Ansible
        run: sudo apt-get install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbook.yml -i "user-ec2@0.0.0.0," Users/User/.ssh/id_rsa.pem # add just when wil be instance
