---
- hosts: backend
  become: true
  tasks:
    - name: Встановлення Node.js
      apt:
        name: nodejs
        state: present
    - name: Копіювання файлів бекенду
      copy:
        src: ./backend/
        dest: /var/www/backend/

- hosts: frontend
  become: true
  tasks:
    - name: Встановлення Node.js для React
      apt:
        name: nodejs
        state: present
    - name: Копіювання файлів фронтенду
      copy:
        src: ./frontend/
        dest: /var/www/frontend/

- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - docker.io
        - prometheus
        - grafana

    - name: Start and enable Docker
      apt:
        name: docker
        state: started
        enabled: yes

    - name: Pull Prometheus Docker image
      docker_image:
        name: prom/prometheus
        source: pull

    - name: Pull Grafana Docker image
      docker_image:
        name: grafana/grafana
        source: pull

    - name: Pull Node Exporter Docker image
      docker_image:
        name: prom/node-exporter
        source: pull

    - name: Create Prometheus config
      copy:
        src: templates/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: root
        group: root
        mode: 0644

    - name: Start Prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus
        state: started
        restart_policy: always
        ports:
          - "9090:9090"

    - name: Start Grafana container
      docker_container:
        name: grafana
        image: grafana/grafana
        state: started
        restart_policy: always
        ports:
           - "3000:3000"

    - name: Start Node Exporter container
      docker_container:
        name: node_exporter
        image: prom/node-exporter
        state: started
        restart_policy: always
        ports:
          - "9100:9100"
