name: Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Install Ansible
        run: sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: ansible-playbook ansible/playbook.yml -i "${{ secrets.EC2_PUBLIC_IP }}," --private-key ${{ secrets.EC2_SSH_KEY }}
